#!/usr/bin/env node
/**
 * Dynamic port allocation for multi-worktree development
 *
 * This script:
 * 1. Finds the first available port pair (30xx for frontend, 31xx for backend)
 * 2. Writes .env.local files for both frontend and backend
 * 3. Outputs the ports for use by npm scripts
 *
 * Usage:
 *   node scripts/dev-ports.mjs           # Setup ports and output JSON
 *   node scripts/dev-ports.mjs --clean   # Remove .env.local files
 *   node scripts/dev-ports.mjs --show    # Show current port config without changing
 */

import { createServer } from 'net';
import { writeFileSync, readFileSync, existsSync, unlinkSync } from 'fs';
import { join, basename } from 'path';

const ROOT_DIR = process.cwd();
const FRONTEND_ENV = join(ROOT_DIR, 'frontend', '.env.local');
const BACKEND_ENV = join(ROOT_DIR, 'backend', '.env.local');

// Port ranges: FE: 3000-3099, BE: 3100-3199
const FE_PORT_BASE = 3000;
const BE_PORT_BASE = 3100;
const PORT_RANGE = 100;

/**
 * Try to bind to a port and return the server if successful
 */
async function tryBindPort(port) {
  return new Promise((resolve) => {
    const server = createServer();
    server.once('error', () => resolve(null));
    server.once('listening', () => resolve(server));
    server.listen(port);
  });
}

/**
 * Find the first available port pair (FE at 30xx, BE at 31xx with same offset)
 */
async function findAvailablePortPair() {
  for (let offset = 0; offset < PORT_RANGE; offset++) {
    const fePort = FE_PORT_BASE + offset;
    const bePort = BE_PORT_BASE + offset;

    // Try to bind both ports
    const feServer = await tryBindPort(fePort);
    if (!feServer) continue;

    const beServer = await tryBindPort(bePort);
    if (!beServer) {
      feServer.close();
      continue;
    }

    // Found an available pair
    return { fePort, bePort, feServer, beServer };
  }

  throw new Error(`No available port pairs found in range ${FE_PORT_BASE}-${FE_PORT_BASE + PORT_RANGE}`);
}

/**
 * Read current ports from .env.local files if they exist
 */
function getCurrentPorts() {
  let fePort = null;
  let bePort = null;

  if (existsSync(FRONTEND_ENV)) {
    const content = readFileSync(FRONTEND_ENV, 'utf-8');
    const portMatch = content.match(/^PORT=(\d+)/m);
    if (portMatch) fePort = parseInt(portMatch[1], 10);
  }

  if (existsSync(BACKEND_ENV)) {
    const content = readFileSync(BACKEND_ENV, 'utf-8');
    const portMatch = content.match(/^PORT=(\d+)/m);
    if (portMatch) bePort = parseInt(portMatch[1], 10);
  }

  return { fePort, bePort };
}

/**
 * Write .env.local files for frontend and backend
 */
function writeEnvFiles(fePort, bePort) {
  // Frontend .env.local - tells Next.js which backend to connect to and which port to use
  const frontendEnv = `# Auto-generated by dev-ports.mjs for multi-worktree support
# Do not commit this file
NEXT_PUBLIC_API_URL=http://localhost:${bePort}/api
PORT=${fePort}
`;
  writeFileSync(FRONTEND_ENV, frontendEnv);

  // Backend .env.local - sets the port and CORS origin
  const backendEnv = `# Auto-generated by dev-ports.mjs for multi-worktree support
# Do not commit this file
PORT=${bePort}
CORS_ORIGIN=http://localhost:${fePort}
`;
  writeFileSync(BACKEND_ENV, backendEnv);
}

/**
 * Clean up .env.local files
 */
function cleanEnvFiles() {
  if (existsSync(FRONTEND_ENV)) {
    unlinkSync(FRONTEND_ENV);
    console.error(`Removed ${FRONTEND_ENV}`);
  }
  if (existsSync(BACKEND_ENV)) {
    unlinkSync(BACKEND_ENV);
    console.error(`Removed ${BACKEND_ENV}`);
  }
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--clean')) {
    cleanEnvFiles();
    return;
  }

  const worktreeName = basename(ROOT_DIR);

  if (args.includes('--show')) {
    const current = getCurrentPorts();
    console.error(`Worktree: ${worktreeName}`);
    console.error(`Current config: FE=${current.fePort || 'none'}, BE=${current.bePort || 'none'}`);
    return;
  }

  // Find first available port pair
  const { fePort, bePort, feServer, beServer } = await findAvailablePortPair();

  // Release the held ports just before we return
  feServer.close();
  beServer.close();

  // Write the env files
  writeEnvFiles(fePort, bePort);

  // Output for use by npm scripts (JSON format for easy parsing)
  const result = {
    worktree: worktreeName,
    frontend: fePort,
    backend: bePort,
    frontendUrl: `http://localhost:${fePort}`,
    backendUrl: `http://localhost:${bePort}`
  };

  console.log(JSON.stringify(result));

  // Also log human-readable info to stderr (doesn't affect JSON parsing)
  console.error(`\n📍 Worktree: ${worktreeName}`);
  console.error(`🌐 Frontend: http://localhost:${fePort}`);
  console.error(`🔧 Backend:  http://localhost:${bePort}/api\n`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
